### PR TITLE
Added :hmac+sha1 HMAC option

### PR DESCRIPTION
**Pull request by shilder**

### CODE REVIEW

**Comment by greut** [comment]
pretty please.

**Comment by st3fan** [comment]
@niwinz Can this be merged and shipped please?

**Comment by greut** [comment]
@st3fan I've been used that instead, https://github.com/funcool/buddy-core/issues/58#issuecomment-430506199

**Comment by wcerfgba** [comment]
I was just about to submit a PR for this! :joy: In my case I needed this for receiving GitHub webhooks. I've added the multimethod implementation myself (nod to @greut and @shilder for sharing this with the community), but would love to see this in the core lib. :smile:

**Pull request merged**
