### PR TITLE
Add in two new Digests 'whirlpool' and 'RIPEMD160'.

### PR DESCRIPTION
**Pull request by dharrigan**
Hi,

Please can this be considered for merging. We use these functions and would love to see them included within the core library.

Thank you.

-=david=-

### CODE REVIEW

**Comment by niwinz** [comment]
Thanks! They will be available on the next version ;)

**Comment by dharrigan** [comment]
You're most welcome. I was thinking of adding the other RIPEMD digests in, what do you think?

**Comment by niwinz** [comment]
Feel free!

**Comment by dharrigan** [comment]
Coolio

Don't let me hold up any release you have planned, but I would hope to include them in the next day or two.

-=david=-

**Pull request merged**
